### ISSUE TITLE
MILESTONE: April 2021

### ISSUE THREAD

**Issue by AigioL** [SteamTools-Team/SteamTools#147]
Here are the milestones we plan to accomplish by April, and then release 2.0 :

# Features
- [ ] ~~起始页~~
    - [ ] ~~UI~~
- [X] 社区加速
    - [X] UI 
- [X] 脚本配置
    - [X] UI 
- [X] 账号切换
    - [X] 基本
    - [ ] 动态头像框GIF/~~APNG~~ 与 ~~动态背景MP4/WEBM~~
        - [x] Native Impl
        - [ ] ~~WebView Impl~~
- [X] 库存游戏
    - [X] UI 
- [X] 本地令牌
    - [X] UI
    - [ ] ~~加密设置~~
- [ ] ~~游戏功能~~
    - [ ] ~~UI~~ 
- [X] 设置
    - [X] 界面设置
        - [X] 语言
        - [X] 主题
        - [x] 字体
    - [X] 基本设置
    - [X] Steam设置
    - [ ] ~~令牌设置~~
- [X] 关于
    - [X] 此软件
    - [X] Q&A
    - [X] 开放源代码许可
    - [ ] ~~联系我们~~
- [X] 云服务
    - [X] 登录与注册
        - [X] UI
        - [X] Mock
        - [x] Test
    - [X] 个人资料
        - [X] UI
        - [x] Mock
        - [X] Test
    - [X] 换绑手机
        - [X] UI
        - [X] Mock
        - [X] Test
    - [ ] ~~注销账号~~
        - [ ] UI 
    - [x] 退出登录
        - [X] UI 
- [ ] NotifyIcon
    - [ ] Windows
    - [ ] macOS
    - [ ] Linux
- [ ] [JumpList](https://docs.microsoft.com/zh-cn/dotnet/api/system.windows.shell.jumplist?view=net-5.0)
    - [X] https://github.com/SteamTools-Team/Avalonia.Win32.JumpLists
    - [ ] ~~显示账号切换中最近几条数据~~

# Improvement
- [X] Hosts 文件写入操作
- [X] 加速失败提示
- [X] 脚本附加方式
- [X] Steam 个人资料XML接口转发
- [X] 令牌与确认上架接口转发
- [X] 增量更新新版本
