### ISSUE TITLE
v2.4.9 ~ v2.5.0 Milestone

### ISSUE THREAD

**Issue by AigioL** [SteamTools-Team/SteamTools#353]
# v2.4.9 Milestone

- [x] 应用内更新机制改进 #352
    - [x] Desktop
    - [x] Android
- [x] 成就管理风险不再提示复选框 #279
- [x] 开机自启失效 #308
- [x] 我的面板中出现垂直滚动条 #233
- [x] 划词翻译脚本适配 #304
- [x] #288
- [x] #320
- [x] #317
- [x] macOS Beta 测试 #296 #196
  - [x] ```FileSystemDesktopMac.InitFileSystem()``` 测试
  ```AppData 目录重定向到``` [NSSearchPathDirectory.LibraryDirectory](https://developer.apple.com/documentation/foundation/nssearchpathdirectory/nslibrarydirectory)
  ```Cache 目录重定向到``` [NSSearchPathDirectory.CachesDirectory](https://developer.apple.com/documentation/foundation/nssearchpathdirectory/nscachesdirectory)
- [x] Android Alpha 测试 #297
  - [x] 本地令牌 #258
- [x] Linux Alpha 测试  #31 #85
- [x] 本地令牌改进
  - [x] 单个令牌导出
    - [x] Android
    - [ ] Desktop [TBD]
  - [x] 导出为二维码
    - [x] Android
    - [x] Desktop
  - [x] 扫码导入
    - [x] Android
    - [ ] Desktop [TBD]
      - [UWP Camera](https://docs.microsoft.com/zh-cn/windows/uwp/audio-video-camera/camera)
  - [x] 修复令牌上移下移不正确 #329
    - [ ] Android [TBD]
    - [x] Desktop
- [x] 第三方快速登录改为新的方案与新增QQ登录渠道 #315
- [x] 翻译工具导入新翻译文本 #316 #300
- [x] 测试
  - [x] 新版本全量更新新逻辑
  - [x] 新的快速登录方式
