### ISSUE TITLE
v2.6.0 Milestone

### ISSUE THREAD

**Issue by AigioL** [SteamTools-Team/SteamTools#378]
# v2.6.0 Milestone

- [ ] ~~桌面端守护进程 [TBD]#302~~
- [x] 托盘右键窗口复制令牌 #334
- [ ] ASF Plus
  - [x] Desktop #313
  - [ ] Android
    - [x] 将 ASF 改为 Library 引用
    - [x] ASP.NET Core 2.x Web Api Running on Xamarin.Android 11
    - [x] Android UI 实现控制台文本框控件 [TextView](https://developer.android.com/reference/android/widget/TextView)
    - [ ] ~~[Android Service](https://developer.android.com/guide/components/services) [TBD]~~
- [ ] 本地令牌改进
  - [ ] ~~应用微件 [TBD]#366~~
    - 应用微件是可以嵌入其他应用（如主屏幕）并接收定期更新的微型应用视图。这些视图称为界面中的微件，您可以使用应用微件提供程序发布微件。能够容纳其他应用微件的应用组件称为应用微件托管应用。下面的屏幕截图显示了音乐应用微件。
      - 参考文献
        - https://developer.android.google.cn/guide/topics/appwidgets?hl=zh-cn#Basics
        - https://developer.android.google.cn/guide/topics/appwidgets/overview?hl=zh-cn
  - [ ] ~~生物识别 [TBD]~~
    - [ ] Android 
      - [生物识别](https://developer.android.google.cn/training/sign-in/biometric-auth?hl=zh-cn)
        - ```借助生物识别因素，可在 Android 平台上实现安全的身份验证。Android 框架包含人脸和指纹生物识别身份验证方式。您可对 Android 进行自定义以支持其他形式的生物识别身份验证方式（例如虹膜）。所有生物识别实现都必须符合安全规范且具有较高的安全评级才能使用 BiometricPrompt 类。衡量生物识别的指标有冒名接受率 (IAR) 和欺骗接受率 (SAR)。```
      - [AndroidX.Biometric](https://developer.android.google.cn/jetpack/androidx/releases/biometric?hl=zh-cn)
      - [显示生物识别身份验证对话框](https://developer.android.google.cn/training/sign-in/biometric-auth?hl=zh-cn)
    - [ ] Windows Desktop
      - [Windows Hello](https://docs.microsoft.com/zh-cn/windows/uwp/security/microsoft-passport)
        - ```Windows Hello 是 Microsoft 为内置于 Windows 10 的新生物识别登录系统所取的名称。 因为它直接内置于操作系统，所以 Windows Hello 允许面部或指纹标识解锁用户的设备。 当用户提供其唯一生物识别标识符来访问特定于设备的凭据时会发生身份验证，这意味着窃取设备的攻击者无法登录它，除非该攻击者具有 PIN。 Windows 安全凭据存储可保护设备上的生物识别数据。 通过使用 Windows Hello 解锁设备，未经授权的用户可以获取其所有 Windows 体验、应用、数据、网站和服务的访问权限。```
