### ISSUE TITLE
v2.4.10 Milestone

### ISSUE THREAD

**Issue by AigioL** [SteamTools-Team/SteamTools#379]
- [x] Android
  - [x] 扫码导入改为 MLKit + CameraX
  - 参考文献
    - https://juejin.cn/post/6950448798208376839
    - https://developers.google.cn/ml-kit/vision/barcode-scanning
    - https://developers.google.cn/ml-kit/vision/barcode-scanning/android#java
    - https://github.com/googlesamples/mlkit/tree/master/android/vision-quickstart
    - https://github.com/googlesamples/mlkit/tree/master/android/material-showcase
  - [x] 导入令牌成功后 Toast 消息未正常显示 #365 #366
  - [x] 从图库中选择二维码图片导入令牌
  - [x] 文件导入选择图片识别二维码导入令牌
  - [x] 导入令牌文件中有包含密码时未能显示密码输入框
  - [x] Android O 以下因为通知渠道导致的启动时闪退 #374 #376 #390
  - [x] 冷启动优化 #367
  - [ ] 确认交易界面绑定逻辑，显示了两个 Loading，无数据时不应显示底部操作区域，数据刷新不正确等
- [x] macOS
  - [ ] ~~UI #369~~
- [x] Linux
  - [x] Arch Linux 上因字体引发的启动时异常 #371 #375 #402
- [x] Shared
  - [x] (服务端)账号绑定后登录不应创建新用户 #377
  - [x] 导入带密码的令牌数据，密码输入文本框窗口无法取消
  - [x] Firefox WebSocket 兼容问题 #382 #384
  - [x] 网络加速中计时 UI 布局错误 #370
- [x] Desktop
  - [x] [Windows 11/WinUI 3 Style](https://docs.microsoft.com/en-us/windows/apps/design/signature-experiences/signature-experiences)
